//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaAlexeiDenis
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Licitatie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Licitatie()
        {
            this.Oferte = new HashSet<Oferte>();
           
        }
    
        public int IDLicitatie { get; set; }
        public System.DateTime DataPornire { get; set; }
        public System.DateTime DataIncheiere { get; set; }
        public decimal PretInitial { get; set; }
        public int IDProdus { get; set; }
    
        public virtual Produse Produse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferte> Oferte { get; set; }

       
    }
}
