//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaAlexeiDenis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produse()
        {
            this.Licitatie = new HashSet<Licitatie>();
        }
    
        public int IDProdus { get; set; }
        public string NumeProdus { get; set; }
        public decimal PretEstimat { get; set; }
        public int CodCategorie { get; set; }
        public string NumeProprietar { get; set; }
        public string Imagine { get; set; }
    
        public virtual CategoriiProduse CategoriiProduse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Licitatie> Licitatie { get; set; }
    }
}
