//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaAlexeiDenis
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Useri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Useri()
        {
            this.Oferte = new HashSet<Oferte>();
            this.UseriRol = new HashSet<UseriRol>();
        }

        public int IdUser { get; set; }
        [Required(ErrorMessage = "Tastati un nume")]
        public string Nume { get; set; }
        [Required(ErrorMessage = "Tastati o adresa de mail")]
        [EmailAddress(ErrorMessage = "Scrieti o adresa de mail valida.")]
        public string Email { get; set; }
        [Required(ErrorMessage ="Tastati un numar de telefon")]
        [RegularExpression(@"^(?<paren>\()?0(?:(?:72|74|75|76|77|78)(?(paren)\))(?<first>\d)(?!\k<first>{6})\d{6}|(?:251|351)(?(paren)\))(?<first>\d)(?!\k<first>{5})\d{5})$",
            ErrorMessage = "Tastati un numar de telefon valid.")]
        public string Telefon { get; set; }
        [Required(ErrorMessage = "Tastati o parola")]
        public string Parola { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferte> Oferte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UseriRol> UseriRol { get; set; }
    }
}
